#!/bin/bash

# PPOM Migration via PostgreSQL directly
# Uses psql to connect to Supabase PostgreSQL

echo "🚀 PPOM Migration - Direct PostgreSQL"
echo "======================================"
echo ""
echo "To apply the migration directly, follow these steps:"
echo ""
echo "1️⃣  Get your PostgreSQL connection string:"
echo "   • Go to: https://app.supabase.com"
echo "   • Select your project"
echo "   • Settings → Database → Connection Pooling"
echo "   • Copy the connection string"
echo ""
echo "2️⃣  Run the migration:"
echo ""
echo "   Option A: Using psql directly"
echo "   ─────────────────────────────"
echo "   psql 'postgresql://user:password@host:5432/database' < add-ppom-columns.sql"
echo ""
echo "   Option B: Using environment variable"
echo "   ────────────────────────────────────"
echo "   export DATABASE_URL='postgresql://user:password@host:5432/database'"
echo "   psql \"\$DATABASE_URL\" < add-ppom-columns.sql"
echo ""
echo "   Option C: Interactive mode"
echo "   ──────────────────────────"
echo "   psql"
echo "   # Then in psql prompt, paste the migration SQL"
echo ""
echo "3️⃣  Verify the migration:"
echo "   psql -c \"SELECT column_name FROM information_schema.columns WHERE table_name='order_items' ORDER BY column_name;\""
echo ""
echo "❓ Alternative: Use Supabase CLI"
echo "──────────────────────────────"
echo "   supabase db push < add-ppom-columns.sql"
echo ""
